import { Person, Task, Reward } from './types';

export const PEOPLE: Person[] = ["Adam", "Nina", "Krzysiek", "Tomek", "Dzieci", "Rodzice", "Wszyscy"];

export const TASKS: Task[] = [
  { id: 't1', name: "Wyjmowanie i wkładanie naczyń", points: 1 },
  { id: 't2', name: "Pranie + suszenie + rozkładanie prania", points: 3 },
  { id: 't3', name: "Sprzątanie łazienki dolnej", points: 3 },
  { id: 't4', name: "Sprzątanie łazienki górnej", points: 3 },
  { id: 't5', name: "Sprzątanie swojego pokoju", points: 2 },
  { id: 't6', name: "Wynoszenie śmieci zmieszanych", points: 1 },
  { id: 't7', name: "Wynoszenie śmieci bio", points: 1 },
  { id: 't8', name: "Wynoszenie śmieci plastik/papier/szkło", points: 1 },
  { id: 't9', name: "Koszenie trawnika w sezonie", points: 5 },
  { id: 't10', name: "Sprzątanie ogrodu w sezonie", points: 5 },
  { id: 't11', name: "Odśnieżanie w sezonie", points: 5 },
  { id: 't12', name: "Mycie podłogi kuchni i salonie", points: 3 },
  { id: 't13', name: "Sprzątanie wiatrołapu", points: 2 },
  { id: 't14', name: "Sprzątanie kurzu w Kuchnia/Salon", points: 2 },
  { id: 't15', name: "Sprzątanie biurka i okolic", points: 2 },
  { id: 't16', name: "Sprzątnięcie brudnych ubrań", points: 2 },
  { id: 't17', name: "Pielenie ogrodu w sezonie", points: 3 },
  { id: 't18', name: "Czyszczenie pralki", points: 3 },
  { id: 't19', name: "Czyszczenie zmywarki", points: 3 },
  { id: 't20', name: "Czyszczenie suszarki", points: 3 },
  { id: 't21', name: "Czyszczenie akwarium", points: 5 },
  { id: 't22', name: "Przecieranie blatów roboczych i stołu po posiłkach", points: 1 },
  { id: 't23', name: "Odkurzanie schodów", points: 2 },
  { id: 't24', name: "Mycie luster w łazienkach i wiatrołapie", points: 3 },
  { id: 't25', name: "Mycie drzwi wejściowych i włączników światła", points: 2 },
  { id: 't26', name: "Zmiana pościeli i powłoczek", points: 3 },
  { id: 't27', name: "Wietrzenie pościeli i materacy", points: 2 },
  { id: 't28', name: "Segregowanie i odkładanie czystych ubrań do swoich szaf", points: 2 },
  { id: 't29', name: "Zmiana pościeli", points: 3 },
  { id: 't30', name: "Wietrzenie/czyszczenie materacy", points: 2 },
  { id: 't31', name: "Zamiatanie i odkurzanie podłogi w garażu/kotłowni", points: 3 },
  { id: 't32', name: "Koszenie chwastów poza trawnikiem", points: 3 },
  { id: 't33', name: "Generalne porządki Kuchni", points: 5 },
  { id: 't34', name: "Generalne porządki Salonu", points: 5 },
  { id: 't35', name: "Generalne porządki Gabinetu", points: 5 },
  { id: 't36', name: "Generalne porządki ogólne", points: 5 },
  { id: 't37', name: "Przegląd ubrań i butów dzieci", points: 3 },
  { id: 't38', name: "Odrabianie zadań domowych z Librusa", points: 2 },
  { id: 't39', name: "Przygotowanie do klasówki / sprawdzianu", points: 3 },
  { id: 't40', name: "Pakowanie plecaka na następny dzień (wg planu lekcji)", points: 1 },
  { id: 't41', name: "Przeczytanie książki papierowej", points: 2 },
  { id: 't42', name: "Zajęcia dodatkowe Angielski", points: 2 },
  { id: 't43', name: "Zajęcia dodatkowe Hiszpański", points: 2 },
  { id: 't44', name: "Siłownia", points: 2 },
  { id: 't45', name: "Zajęcia dodatkowe programowanie", points: 2 },
  { id: 't46', name: "Zajęcia dodatkowe TUS", points: 2 },
  { id: 't47', name: "Badminton", points: 2 },
  { id: 't48', name: "Basen", points: 2 },
];

export const REWARDS: Reward[] = [
  { id: 'r1', name: "Odblokowanie komputera", points: 10 },
  { id: 'r2', name: "Odblokowanie komputera na dodatkowy czas (+30 min)", points: 5 },
  { id: 'r3', name: "Odblokowanie TV", points: 10 },
  { id: 'r4', name: "Odblokowanie TV na dodatkowy czas (+30 min)", points: 5 },
  { id: 'r5', name: "Odblokowanie Youtube/instagram/cokolwiek", points: 5 },
  { id: 'r6', name: "Słodycze", points: 5 },
  { id: 'r7', name: "Wyjście do kina", points: 30 },
  { id: 'r8', name: "Późniejsze pójście spać (+30/60 min w weekend)", points: 15 },
  { id: 'r9', name: "Kupon na „Zwolnienie z jednego obowiązku”", points: 20 },
  { id: 'r10', name: "Dzień bez budzika / bez porannych zadań (sobota)", points: 25 },
  { id: 'r11', name: "Kupon na veto (odrzucenie jednej prośby)", points: 20 },
  { id: 'r12', name: "Doładowanie wirtualnej waluty (Robuxy, V-Dolce itp.)", points: 40 },
  { id: 'r13', name: "Wypłata kieszonkowego / gotówka ekstra", points: 50 },
  { id: 'r14', name: "Zakup nowej gry", points: 100 },
  { id: 'r15', name: "Zakup książki, mangi, komiksu lub gadżetu/zabawki", points: 40 },
  { id: 'r16', name: "Wybór menu na obiad dla całej rodziny", points: 15 },
  { id: 'r17', name: "Zamówienie jedzenia z dostawą na życzenie", points: 30 },
  { id: 'r18', name: "Wyjście na lody / bubble tea po szkole", points: 15 },
  { id: 'r19', name: "Zakup przekąsek \"premium\" do weekendowego seansu", points: 10 },
  { id: 'r20', name: "„Czas sam na sam z wybranym rodzicem”", points: 25 },
  { id: 'r21', name: "Rodzinny wieczór gier/wideo (własne zasady)", points: 20 },
  { id: 'r22', name: "Prywatny szofer (Podwózka autem bez autobusu/roweru)", points: 15 },
  { id: 'r23', name: "Kupon „Śniadanie do łóżka”", points: 20 },
  { id: 'r24', name: "Kupon „Cisza w pokoju” (gwarancja braku wchodzenia bez pukania)", points: 10 },
  { id: 'r25', name: "Wybór muzyki w samochodzie", points: 5 },
  { id: 'r26', name: "Ekstra budżet na wycieczce szkolnej", points: 30 },
  { id: 'r27', name: "Kupon na przełożenie terminu (o 24h bez konsekwencji)", points: 10 },
  { id: 'r28', name: "Dzień bez pytania o szkołę (24 godziny)", points: 15 },
  { id: 'r29', name: "Nocny seans filmowy (oglądanie do późna)", points: 20 },
  { id: 'r30', name: "Zwolnienie ze spaceru / wyjścia rodzinnego", points: 15 },
];
